# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/com.unity.gis.streaming-framework.rc
  name: com.unity.gis.streaming-framework.rc
  description: "A streaming framework for geospatial data"
  labels:
    costcenter: "5029"
  tags:
    - planned-public
  links:
    - url: https://unity.slack.com/messages/C01RU3BHA3S/
      title: "#aa-geospatial-devs"
      icon: chat
spec:
  type: unity-package
  lifecycle: experimental
  owner: unity-technologies/dt-members
